using System.Collections;
using Cysharp.Threading.Tasks;
using WiSdom.DesignPattern;
using WiSdom.SaveSystem.Data;

namespace WiSdom.SaveSystem
{
    public class DataManager : SingletonMonoBehaviour<DataManager>
    {
        #region Fields
        public static bool ISALLDATALOADED = false;
        public static bool ISDATASAVING = false;
        #endregion

        #region Methods
        protected override void Awake()
        {
            base.Awake();

        }
        IEnumerator Start()
        {
            ISALLDATALOADED = false;
            yield return LoadAllData();
            // Your data control logic here


            ISALLDATALOADED = true;
        }

        #endregion


        /* --------------------WARNING--------------------
        // Do not modify this region
        // Generated by Roslyn
        */
        #region Auto Generators

        #region Field Generators
		public VersionData VersionData;
		public SettingsData SettingsData;
		public UserInfo UserInfo;
        #endregion

        #region Data Control
        public async UniTaskVoid LoadAllData()
        {
            #region Load Data
			await LoadVersionDataData();
			await LoadSettingsDataData();
			await LoadUserInfoData();
			#endregion

        }
        public async UniTaskVoid SaveAllData()
        {
            ISDATASAVING = true;
            #region Save Data
			await SaveVersionDataData();
			await SaveSettingsDataData();
			await SaveUserInfoData();
			#endregion
            ISDATASAVING = false;
        }

        public void ClearAllData()
        {
            #region Clear Data
			SaveManager.ClearData("VersionData");
			SaveManager.ClearData("SettingsData");
			SaveManager.ClearData("UserInfo");
			#endregion
        }
        #endregion
        #region Methods Generators
		public async UniTask LoadVersionDataData()
		{
			VersionData = await SaveManager.LoadData<VersionData>("VersionData");
		}
		public async UniTask SaveVersionDataData()
		{
			await SaveManager.SaveData(VersionData, "VersionData");
		}
		public void ClearVersionDataData()
		{
			SaveManager.ClearData("VersionData");
		}
		public async UniTask LoadSettingsDataData()
		{
			SettingsData = await SaveManager.LoadData<SettingsData>("SettingsData");
		}
		public async UniTask SaveSettingsDataData()
		{
			await SaveManager.SaveData(SettingsData, "SettingsData");
		}
		public void ClearSettingsDataData()
		{
			SaveManager.ClearData("SettingsData");
		}
		public async UniTask LoadUserInfoData()
		{
			UserInfo = await SaveManager.LoadData<UserInfo>("UserInfo");
		}
		public async UniTask SaveUserInfoData()
		{
			await SaveManager.SaveData(UserInfo, "UserInfo");
		}
		public void ClearUserInfoData()
		{
			SaveManager.ClearData("UserInfo");
		}
		#endregion
        #endregion
        // --------------------THE END--------------------
    }
}